version: '3.7'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
    volumes: 
      - /opt/plex:/config
      - /mnt/filmy:/data/movies
    restart: unless-stopped
  ispy:
    image: doitandbedone/ispyagentdvr
    container_name: ispy
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    volumes:
      - /opt/ispy/config:/agent/Media/XML
      - /opt/ispy/media:/agent/Media/WebServerRoot/Media
      - /opt/ispy/commands:/agent/Commands
    environment:
      - TZ=Europe/Prague
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Prague/Europe
    volumes:
      - /opt/homebridge:/homebridge
  mongo:
    image: mongo:3.6
    container_name: mongo
    networks:
      - unifi
    restart: unless-stopped
    volumes: 
      - /opt/db:/data/db
      - /opt/dbcfg:/data/configdb
  controller:
    image: jacobalberty/unifi
    container_name: controller
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: unless-stopped
    volumes:
      - /opt/unifi/dir:/unifi
      - /opt/unifi/data/unifi-data
      - /opt/unifi/log:/unifi/log
      - /opt/unifi/cert:/unifi/cert
      - /opt/unifi/init:/unifi/init.d
      - /opt/unifi/run:/var/run/unifi
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - 33478:3478/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 8880:8880/tcp
      - 8843:8843/tcp
      - 10001:10001/udp
  logs:
    image: bash
    container_name: logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: unless-stopped
    volumes:
      - /opt/unifi/log:/unifi/log   
networks:
    unifi:
